/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ExcalidrawLatexTextInputPlugin
});
module.exports = __toCommonJS(main_exports);
var import_state = require("@codemirror/state");
var import_view2 = require("@codemirror/view");
var import_language = require("@codemirror/language");
var import_common = require("@lezer/common");
var import_obsidian = require("obsidian");

// src/latex-snippet-extension.ts
var import_view = require("@codemirror/view");

// src/latex-suite-snippets.ts
var SNIPPET_VARIABLES = {
  GREEK: [
    "alpha",
    "beta",
    "gamma",
    "Gamma",
    "delta",
    "Delta",
    "epsilon",
    "varepsilon",
    "zeta",
    "theta",
    "Theta",
    "vartheta",
    "iota",
    "kappa",
    "lambda",
    "Lambda",
    "sigma",
    "Sigma",
    "upsilon",
    "Upsilon",
    "omega",
    "Omega"
  ].join("|"),
  SYMBOL: [
    "infty",
    "sum",
    "prod",
    "lim",
    "pm",
    "mp",
    "dots",
    "nabla",
    "times",
    "cdot",
    "parallel",
    "equiv",
    "neq",
    "geq",
    "leq",
    "gg",
    "ll",
    "sim",
    "simeq",
    "propto",
    "to",
    "mapsto",
    "implies",
    "impliedby",
    "cap",
    "cup",
    "in",
    "notin",
    "setminus",
    "subseteq",
    "supseteq",
    "emptyset"
  ].join("|"),
  MORE_SYMBOLS: [
    "mathcal\\{L\\}",
    "mathcal\\{H\\}",
    "mathbb\\{C\\}",
    "mathbb\\{R\\}",
    "mathbb\\{Z\\}",
    "mathbb\\{N\\}"
  ].join("|"),
  ACCENT: "hat|bar|dot|ddot|tilde|underline|vec"
};
var latexSuiteSnippets = [
  { trigger: "mk", replacement: "$$0$", options: "tA" },
  { trigger: "dm", replacement: "$$\n	$0\n$$", options: "tAw" },
  { trigger: /(?<=\S.*)dm/, replacement: "\n$$\n	$0\n$$", options: "tAw", priority: 1 },
  { trigger: /([^\\])beg/, replacement: "[[0]]\\begin{$0}\n	$1\n\\end{$0}", options: "MA" },
  { trigger: /([^\\])beg/, replacement: "[[0]]\\begin{$0} $1 \\end{$0}", options: "nA" },
  { trigger: "@a", replacement: "\\alpha", options: "mA" },
  { trigger: "@b", replacement: "\\beta", options: "mA" },
  { trigger: "@g", replacement: "\\gamma", options: "mA" },
  { trigger: "@G", replacement: "\\Gamma", options: "mA" },
  { trigger: "@d", replacement: "\\delta", options: "mA" },
  { trigger: "@D", replacement: "\\Delta", options: "mA" },
  { trigger: "@e", replacement: "\\epsilon", options: "mA" },
  { trigger: ":e", replacement: "\\varepsilon", options: "mA" },
  { trigger: "@z", replacement: "\\zeta", options: "mA" },
  { trigger: "@t", replacement: "\\theta", options: "mA" },
  { trigger: "@T", replacement: "\\Theta", options: "mA" },
  { trigger: ":t", replacement: "\\vartheta", options: "mA" },
  { trigger: "@i", replacement: "\\iota", options: "mA" },
  { trigger: "@k", replacement: "\\kappa", options: "mA" },
  { trigger: "@l", replacement: "\\lambda", options: "mA" },
  { trigger: "@L", replacement: "\\Lambda", options: "mA" },
  { trigger: "@s", replacement: "\\sigma", options: "mA" },
  { trigger: "@S", replacement: "\\Sigma", options: "mA" },
  { trigger: "@u", replacement: "\\upsilon", options: "mA" },
  { trigger: "@U", replacement: "\\Upsilon", options: "mA" },
  { trigger: "@o", replacement: "\\omega", options: "mA" },
  { trigger: "@O", replacement: "\\Omega", options: "mA" },
  { trigger: "ome", replacement: "\\omega", options: "mA" },
  { trigger: "Ome", replacement: "\\Omega", options: "mA" },
  { trigger: "text", replacement: "\\text{$0}$1", options: "mA" },
  { trigger: '"', replacement: "\\text{$0}$1", options: "mA" },
  { trigger: "sr", replacement: "^{2}", options: "mA" },
  { trigger: "cb", replacement: "^{3}", options: "mA" },
  { trigger: "rd", replacement: "^{$0}$1", options: "mA" },
  { trigger: "_", replacement: "_{$0}$1", options: "mA" },
  { trigger: "sts", replacement: "_\\text{$0}", options: "mA" },
  { trigger: "sq", replacement: "\\sqrt{ $0 }$1", options: "mA" },
  {
    trigger: /((?:\\[A-Za-z]+|[A-Za-z]+|\d+(?:\.\d+)?|\([^()]*\)|\{[^{}]*\}|\[[^\[\]]*])(?:_(?:\{[^{}]*\}|[A-Za-z0-9]+)|\^(?:\{[^{}]*\}|[A-Za-z0-9]+))*)\//,
    replacement: "\\frac{[[0]]}{$0}",
    options: "mA",
    priority: 2,
    description: "Turn a preceding atom followed by / into a fraction"
  },
  { trigger: "//", replacement: "\\frac{$0}{$1}$2", options: "mA" },
  { trigger: "ee", replacement: "e^{ $0 }$1", options: "mA" },
  { trigger: "invs", replacement: "^{-1}", options: "mA" },
  { trigger: /([^\\])(exp|log|ln)/, replacement: "[[0]]\\[[1]]", options: "rmA" },
  { trigger: "conj", replacement: "^{*}", options: "mA" },
  { trigger: "Re", replacement: "\\mathrm{Re}", options: "mA" },
  { trigger: "Im", replacement: "\\mathrm{Im}", options: "mA" },
  { trigger: "bf", replacement: "\\mathbf{$0}", options: "mA" },
  { trigger: "rm", replacement: "\\mathrm{$0}$1", options: "mA" },
  { trigger: /([^\\])(det)/, replacement: "[[0]]\\[[1]]", options: "rmA" },
  { trigger: "trace", replacement: "\\mathrm{Tr}", options: "mA" },
  { trigger: "([a-zA-Z])hat", replacement: "\\hat{[[0]]}", options: "rmA" },
  { trigger: "([a-zA-Z])bar", replacement: "\\bar{[[0]]}", options: "rmA" },
  { trigger: "([a-zA-Z])dot", replacement: "\\dot{[[0]]}", options: "rmA", priority: -1 },
  { trigger: "([a-zA-Z])ddot", replacement: "\\ddot{[[0]]}", options: "rmA", priority: 1 },
  { trigger: "([a-zA-Z])tilde", replacement: "\\tilde{[[0]]}", options: "rmA" },
  { trigger: "([a-zA-Z])und", replacement: "\\underline{[[0]]}", options: "rmA" },
  { trigger: "([a-zA-Z])vec", replacement: "\\vec{[[0]]}", options: "rmA" },
  { trigger: "([a-zA-Z]),\\.", replacement: "\\mathbf{[[0]]}", options: "rmA" },
  { trigger: "([a-zA-Z])\\.,", replacement: "\\mathbf{[[0]]}", options: "rmA" },
  { trigger: "\\\\(${GREEK}),\\.", replacement: "\\boldsymbol{\\[[0]]}", options: "rmA" },
  { trigger: "\\\\(${GREEK})\\.,", replacement: "\\boldsymbol{\\[[0]]}", options: "rmA" },
  { trigger: "hat", replacement: "\\hat{$0}$1", options: "mA" },
  { trigger: "bar", replacement: "\\bar{$0}$1", options: "mA" },
  { trigger: "dot", replacement: "\\dot{$0}$1", options: "mA", priority: -1 },
  { trigger: "ddot", replacement: "\\ddot{$0}$1", options: "mA" },
  { trigger: "cdot", replacement: "\\cdot", options: "mA" },
  { trigger: "tilde", replacement: "\\tilde{$0}$1", options: "mA" },
  { trigger: "und", replacement: "\\underline{$0}$1", options: "mA" },
  { trigger: "vec", replacement: "\\vec{$0}$1", options: "mA" },
  { trigger: "pmod", replacement: "\\pmod{${0:n}}$1", options: "mA" },
  { trigger: "(\\\\${GREEK}|[A-Za-z])(\\d)", replacement: "[[0]]_{[[1]]}", options: "rmA", priority: -1 },
  { trigger: "(\\\\${GREEK}|[A-Za-z])_{(\\d+)}(\\d)", replacement: "[[0]]_{[[1]][[2]]}", options: "rmA", priority: -1 },
  { trigger: "\\\\(${ACCENT})\\{(\\\\${GREEK}|[A-Za-z])\\}(\\d)", replacement: "\\[[0]]{[[1]]}_{[[2]]}", options: "rmA", priority: -1 },
  { trigger: "\\\\(${ACCENT})\\{(\\\\${GREEK}|[A-Za-z])\\}_\\{(\\d+)\\}(\\d)", replacement: "\\[[0]]{[[1]]}_{[[2]][[3]]}", options: "rmA", priority: -1 },
  { trigger: "\\\\(${ACCENT})\\{\\\\(${ACCENT})\\{(\\\\${GREEK}|[A-Za-z])\\}\\}(\\d)", replacement: "\\[[0]]{\\[[1]]{[[2]]}}_{[[3]]}", options: "rmA", priority: -1 },
  { trigger: "\\\\(${ACCENT})\\{\\\\(${ACCENT})\\{(\\\\${GREEK}|[A-Za-z])\\}\\}_\\{(\\d+)\\}(\\d)", replacement: "\\[[0]]{\\[[1]]{[[2]]}}_{[[3]][[4]]}", options: "rmA", priority: -1 },
  { trigger: "xnn", replacement: "x_{n}", options: "mA" },
  { trigger: "\\xii", replacement: "x_{i}", options: "mA", priority: 1 },
  { trigger: "xjj", replacement: "x_{j}", options: "mA" },
  { trigger: "xp1", replacement: "x_{n+1}", options: "mA" },
  { trigger: "ynn", replacement: "y_{n}", options: "mA" },
  { trigger: "yii", replacement: "y_{i}", options: "mA" },
  { trigger: "yjj", replacement: "y_{j}", options: "mA" },
  { trigger: "ooo", replacement: "\\infty", options: "mA" },
  { trigger: "sum", replacement: "\\sum", options: "mA" },
  { trigger: "prod", replacement: "\\prod", options: "mA" },
  { trigger: "\\sum", replacement: "\\sum_{${0:i}=${1:1}}^{${2:N}} $3", options: "m" },
  { trigger: "\\prod", replacement: "\\prod_{${0:i}=${1:1}}^{${2:N}} $3", options: "m" },
  { trigger: "lim", replacement: "\\lim_{ ${0:n} \\to ${1:\\infty} } $2", options: "mA" },
  { trigger: "+-", replacement: "\\pm", options: "mA" },
  { trigger: "-+", replacement: "\\mp", options: "mA" },
  { trigger: "...", replacement: "\\dots", options: "mA" },
  { trigger: "nabl", replacement: "\\nabla", options: "mA" },
  { trigger: "xx", replacement: "\\times", options: "mA" },
  { trigger: "**", replacement: "\\cdot", options: "mA" },
  { trigger: "para", replacement: "\\parallel", options: "mA" },
  { trigger: "===", replacement: "\\equiv", options: "mA" },
  { trigger: "!=", replacement: "\\neq", options: "mA" },
  { trigger: ">=", replacement: "\\geq", options: "mA" },
  { trigger: "<=", replacement: "\\leq", options: "mA" },
  { trigger: ">>", replacement: "\\gg", options: "mA" },
  { trigger: "<<", replacement: "\\ll", options: "mA" },
  { trigger: "simm", replacement: "\\sim", options: "mA" },
  { trigger: "sim=", replacement: "\\simeq", options: "mA" },
  { trigger: "prop", replacement: "\\propto", options: "mA" },
  { trigger: "<->", replacement: "\\leftrightarrow ", options: "mA" },
  { trigger: "->", replacement: "\\to", options: "mA" },
  { trigger: "!>", replacement: "\\mapsto", options: "mA" },
  { trigger: "=>", replacement: "\\implies", options: "mA" },
  { trigger: "=<", replacement: "\\impliedby", options: "mA" },
  { trigger: "and", replacement: "\\cap", options: "mA" },
  { trigger: "orr", replacement: "\\cup", options: "mA" },
  { trigger: "inn", replacement: "\\in", options: "mA" },
  { trigger: "notin", replacement: "\\not\\in", options: "mA" },
  { trigger: "\\\\\\", replacement: "\\setminus", options: "mA" },
  { trigger: "sub=", replacement: "\\subseteq", options: "mA" },
  { trigger: "sup=", replacement: "\\supseteq", options: "mA" },
  { trigger: "eset", replacement: "\\emptyset", options: "mA" },
  { trigger: "set", replacement: "\\{ $0 \\}$1", options: "mA" },
  { trigger: "e\\xi sts", replacement: "\\exists", options: "mA", priority: 1 },
  { trigger: "LL", replacement: "\\mathcal{L}", options: "mA" },
  { trigger: "HH", replacement: "\\mathcal{H}", options: "mA" },
  { trigger: "CC", replacement: "\\mathbb{C}", options: "mA" },
  { trigger: "RR", replacement: "\\mathbb{R}", options: "mA" },
  { trigger: "ZZ", replacement: "\\mathbb{Z}", options: "mA" },
  { trigger: "NN", replacement: "\\mathbb{N}", options: "mA" },
  { trigger: "([^\\\\])(${GREEK})", replacement: "[[0]]\\[[1]]", options: "rmA" },
  { trigger: "([^\\\\])(${SYMBOL})", replacement: "[[0]]\\[[1]]", options: "rmA" },
  { trigger: "\\\\(${GREEK}|${SYMBOL}|${MORE_SYMBOLS})([A-Za-z])", replacement: "\\[[0]] [[1]]", options: "rmA" },
  { trigger: "\\\\(${GREEK}|${SYMBOL}) sr", replacement: "\\[[0]]^{2}", options: "rmA" },
  { trigger: "\\\\(${GREEK}|${SYMBOL}) cb", replacement: "\\[[0]]^{3}", options: "rmA" },
  { trigger: "\\\\(${GREEK}|${SYMBOL}) rd", replacement: "\\[[0]]^{$0}$1", options: "rmA" },
  { trigger: "\\\\(${GREEK}) hat", replacement: "\\hat{\\[[0]]}", options: "rmA" },
  { trigger: "\\\\(${GREEK}) dot", replacement: "\\dot{\\[[0]]}", options: "rmA" },
  { trigger: "\\\\(${GREEK}) bar", replacement: "\\bar{\\[[0]]}", options: "rmA" },
  { trigger: "\\\\(${GREEK}) vec", replacement: "\\vec{\\[[0]]}", options: "rmA" },
  { trigger: "\\\\(${GREEK}) tilde", replacement: "\\tilde{\\[[0]]}", options: "rmA" },
  { trigger: "\\\\(${GREEK}) und", replacement: "\\underline{\\[[0]]}", options: "rmA" },
  { trigger: "par", replacement: "\\frac{ \\partial ${0:y} }{ \\partial ${1:x} } $2", options: "m" },
  { trigger: /pa([A-Za-z])([A-Za-z])/, replacement: "\\frac{ \\partial [[0]] }{ \\partial [[1]] } ", options: "rm" },
  { trigger: "ddt", replacement: "\\frac{d}{dt} ", options: "mA" },
  { trigger: /([^\\])int/, replacement: "[[0]]\\int", options: "mA", priority: -1 },
  { trigger: "\\int", replacement: "\\int $0 \\, d${1:x} $2", options: "m" },
  { trigger: "dint", replacement: "\\int_{${0:0}}^{${1:1}} $2 \\, d${3:x} $4", options: "mA" },
  { trigger: "oint", replacement: "\\oint", options: "mA" },
  { trigger: "iint", replacement: "\\iint", options: "mA" },
  { trigger: "iiint", replacement: "\\iiint", options: "mA" },
  { trigger: "oinf", replacement: "\\int_{0}^{\\infty} $0 \\, d${1:x} $2", options: "mA" },
  { trigger: "infi", replacement: "\\int_{-\\infty}^{\\infty} $0 \\, d${1:x} $2", options: "mA" },
  { trigger: /([^\\])(arcsin|sin|arccos|cos|arctan|tan|csc|sec|cot)/, replacement: "[[0]]\\[[1]]", options: "rmA" },
  { trigger: /\\(arcsin|sin|arccos|cos|arctan|tan|csc|sec|cot)([A-Za-gi-z])/, replacement: "\\[[0]] [[1]]", options: "rmA" },
  { trigger: /\\(sinh|cosh|tanh|coth)([A-Za-z])/, replacement: "\\[[0]] [[1]]", options: "rmA" },
  { trigger: /(arccsc|arcsec|arccot)/, replacement: "\\operatorname{[[0]]}$0", options: "mA", priority: 1 },
  { trigger: "U", replacement: "\\underbrace{ ${VISUAL} }_{ $0 }", options: "mA" },
  { trigger: "O", replacement: "\\overbrace{ ${VISUAL} }^{ $0 }", options: "mA" },
  { trigger: "B", replacement: "\\underset{ $0 }{ ${VISUAL} }", options: "mA" },
  { trigger: "C", replacement: "\\cancel{ ${VISUAL} }", options: "mA" },
  { trigger: "K", replacement: "\\cancelto{ $0 }{ ${VISUAL} }", options: "mA" },
  { trigger: "S", replacement: "\\sqrt{ ${VISUAL} }", options: "mA" },
  { trigger: "kbt", replacement: "k_{B}T", options: "mA" },
  { trigger: "msun", replacement: "M_{\\odot}", options: "mA" },
  { trigger: "dag", replacement: "^{\\dagger}", options: "mA" },
  { trigger: "o+", replacement: "\\oplus ", options: "mA" },
  { trigger: "ox", replacement: "\\otimes ", options: "mA" },
  { trigger: "bra", replacement: "\\bra{$0} $1", options: "mA" },
  { trigger: "ket", replacement: "\\ket{$0} $1", options: "mA" },
  { trigger: "brk", replacement: "\\braket{ $0 | $1 } $2", options: "mA" },
  { trigger: "outer", replacement: "\\ket{${0:\\psi}} \\bra{${0:\\psi}} $1", options: "mA" },
  { trigger: "pu", replacement: "\\pu{ $0 }", options: "mA" },
  { trigger: "cee", replacement: "\\ce{ $0 }", options: "mA" },
  { trigger: "he4", replacement: "{}^{4}_{2}He ", options: "mA" },
  { trigger: "he3", replacement: "{}^{3}_{2}He ", options: "mA" },
  { trigger: "iso", replacement: "{}^{${0:4}}_{${1:2}}${2:He}", options: "mA" },
  { trigger: /([pbBvV]mat)/, replacement: "\\begin{[[0]]rix}\n$0\n\\end{[[0]]rix}", options: "rMA" },
  { trigger: /(matrix|cases|align|array)/, replacement: "\\begin{[[0]]}\n$0\n\\end{[[0]]}", options: "rMA" },
  { trigger: /([pbBvV]mat)/, replacement: "\\begin{[[0]]rix}$0\\end{[[0]]rix}", options: "rnA" },
  { trigger: /(matrix|cases|align|array)/, replacement: "\\begin{[[0]]}$0\\end{[[0]]}", options: "rnA" },
  { trigger: "avg", replacement: "\\langle $0 \\rangle $1", options: "mA" },
  { trigger: "norm", replacement: "\\lvert $0 \\rvert $1", options: "mA", priority: 1 },
  { trigger: "Norm", replacement: "\\lVert $0 \\rVert $1", options: "mA", priority: 1 },
  { trigger: "ceil", replacement: "\\lceil $0 \\rceil $1", options: "mA" },
  { trigger: "floor", replacement: "\\lfloor $0 \\rfloor $1", options: "mA" },
  { trigger: "mod", replacement: "|$0|$1", options: "mA" },
  { trigger: "(", replacement: "(${VISUAL})", options: "mA" },
  { trigger: "[", replacement: "[${VISUAL}]", options: "mA" },
  { trigger: "{", replacement: "{${VISUAL}}", options: "mA" },
  { trigger: "(", replacement: "($0)$1", options: "mA" },
  { trigger: "{", replacement: "{$0}$1", options: "mA" },
  { trigger: "[", replacement: "[$0]$1", options: "mA" },
  { trigger: "lr(", replacement: "\\left( $0 \\right) $1", options: "mA" },
  { trigger: "lr{", replacement: "\\left\\{ $0 \\right\\} $1", options: "mA" },
  { trigger: "lr[", replacement: "\\left[ $0 \\right] $1", options: "mA" },
  { trigger: "lr|", replacement: "\\left| $0 \\right| $1", options: "mA" },
  { trigger: "lra", replacement: "\\left< $0 \\right> $1", options: "mA" },
  { trigger: "tayl", replacement: "${0:f}(${1:x} + ${2:h}) = ${0:f}(${1:x}) + ${0:f}'(${1:x})${2:h} + ${0:f}''(${1:x}) \\frac{${2:h}^{2}}{2!} + \\dots$3", options: "mA" },
  {
    trigger: /iden(\d)/,
    replacement: (match) => {
      const size = Number(match[1]);
      const rows = Array.from({ length: size }, (_, row) => {
        return Array.from({ length: size }, (_2, col) => row === col ? "1" : "0").join(" & ");
      });
      return `\\begin{pmatrix}
${rows.join(" \\\\\n")}
\\end{pmatrix}`;
    },
    options: "mA"
  },
  {
    trigger: /(?<=(?:\n|^)[ \t]*>*)(?<marker>\d+[.)]|[-*+])(?<whitespace>[ \t]+)(?<text>.*)dm/,
    replacement: (match) => {
      var _a, _b, _c, _d;
      const groups = (_a = match.groups) != null ? _a : {};
      const marker = (_b = groups.marker) != null ? _b : "";
      const whitespace = (_c = groups.whitespace) != null ? _c : "";
      const text = (_d = groups.text) != null ? _d : "";
      const firstLine = marker + whitespace + text;
      const indent = " ".repeat(marker.length) + whitespace;
      return `${firstLine}
${indent}$$
${indent}	$0
${indent}$$`;
    },
    options: "rtA",
    priority: 2
  }
];
var latex_suite_snippets_default = latexSuiteSnippets;

// src/latex-snippet-extension.ts
var SNIPPET_USER_EVENT = "input.complete";
function createLatexSnippetExtension(snippets) {
  return [
    import_view.keymap.of([
      {
        key: "Tab",
        run: (view) => expandBestSnippet(view, snippets, false)
      }
    ]),
    import_view.ViewPlugin.fromClass(
      class {
        constructor(view) {
          this.view = view;
          this.timer = null;
        }
        update(update) {
          if (!update.docChanged || !this.view.hasFocus) {
            return;
          }
          if (update.transactions.some((transaction) => transaction.isUserEvent(SNIPPET_USER_EVENT))) {
            return;
          }
          if (this.timer !== null) {
            window.clearTimeout(this.timer);
          }
          this.timer = window.setTimeout(() => {
            this.timer = null;
            expandBestSnippet(this.view, snippets, true);
          }, 0);
        }
        destroy() {
          if (this.timer !== null) {
            window.clearTimeout(this.timer);
          }
        }
      }
    )
  ];
}
function expandBestSnippet(view, snippets, autoOnly) {
  const snippetMatch = findBestSnippetMatch(view, snippets, autoOnly);
  if (!snippetMatch) {
    return false;
  }
  const replacement = prepareReplacement(snippetMatch.snippet, snippetMatch.match);
  const selection = replacement.selectionFrom === null || replacement.selectionTo === null ? void 0 : {
    anchor: snippetMatch.from + replacement.selectionFrom,
    head: snippetMatch.from + replacement.selectionTo
  };
  view.dispatch({
    changes: {
      from: snippetMatch.from,
      to: snippetMatch.to,
      insert: replacement.text
    },
    selection,
    userEvent: SNIPPET_USER_EVENT
  });
  return true;
}
function findBestSnippetMatch(view, snippets, autoOnly) {
  var _a;
  const selection = view.state.selection.main;
  if (!selection.empty) {
    return null;
  }
  const cursor = selection.head;
  const textBeforeCursor = view.state.doc.sliceString(0, cursor);
  const context = getMathContext(textBeforeCursor);
  const matches = [];
  snippets.forEach((snippet, order) => {
    if (autoOnly && !snippet.options.includes("A")) {
      return;
    }
    if (!snippetAppliesToContext(snippet, context)) {
      return;
    }
    const match = matchSnippetTrigger(snippet, textBeforeCursor);
    if (!match) {
      return;
    }
    matches.push({
      snippet,
      from: cursor - match.length,
      to: cursor,
      match: match.regexMatch,
      order
    });
  });
  matches.sort((left, right) => {
    var _a2, _b;
    const priorityDelta = ((_a2 = right.snippet.priority) != null ? _a2 : 0) - ((_b = left.snippet.priority) != null ? _b : 0);
    if (priorityDelta !== 0) {
      return priorityDelta;
    }
    const lengthDelta = right.to - right.from - (left.to - left.from);
    if (lengthDelta !== 0) {
      return lengthDelta;
    }
    return left.order - right.order;
  });
  return (_a = matches[0]) != null ? _a : null;
}
function snippetAppliesToContext(snippet, context) {
  const options = snippet.options;
  const textAllowed = options.includes("t");
  const inlineAllowed = options.includes("n");
  const displayAllowed = options.includes("M");
  const mathAllowed = options.includes("m") || inlineAllowed || displayAllowed;
  if (displayAllowed && context === "display") {
    return true;
  }
  if (inlineAllowed && context === "inline") {
    return true;
  }
  if (mathAllowed && !inlineAllowed && !displayAllowed && context !== "text") {
    return true;
  }
  if (textAllowed && context === "text") {
    return true;
  }
  return !textAllowed && !mathAllowed;
}
function matchSnippetTrigger(snippet, textBeforeCursor) {
  if (snippet.trigger instanceof RegExp || snippet.options.includes("r")) {
    const regex = snippet.trigger instanceof RegExp ? snippet.trigger : new RegExp(expandSnippetVariables(snippet.trigger));
    const anchored = new RegExp(`${regex.source}$`, regex.flags.replace(/[gy]/g, ""));
    const match = anchored.exec(textBeforeCursor);
    if (!match) {
      return null;
    }
    return {
      length: match[0].length,
      regexMatch: match
    };
  }
  if (!textBeforeCursor.endsWith(snippet.trigger)) {
    return null;
  }
  return {
    length: snippet.trigger.length,
    regexMatch: null
  };
}
function prepareReplacement(snippet, match) {
  const rawReplacement = typeof snippet.replacement === "function" ? snippet.replacement(match != null ? match : [""]) : snippet.replacement;
  const withMatchGroups = rawReplacement.replace(/\[\[(\d+)]]/g, (_, index) => {
    var _a;
    return (_a = match == null ? void 0 : match[Number(index) + 1]) != null ? _a : "";
  });
  return resolvePlaceholders(withMatchGroups);
}
function resolvePlaceholders(replacement) {
  var _a;
  let text = "";
  let cursor = 0;
  let selectionFrom = null;
  let selectionTo = null;
  const placeholderPattern = /\$\{VISUAL}|\$\{(\d+):([^}]*)}|\$(\d+)/g;
  let match;
  let lastIndex = 0;
  while ((match = placeholderPattern.exec(replacement)) !== null) {
    const literal = replacement.slice(lastIndex, match.index);
    text += literal;
    cursor += literal.length;
    const defaultValue = (_a = match[2]) != null ? _a : "";
    if (selectionFrom === null) {
      selectionFrom = cursor;
      selectionTo = cursor + defaultValue.length;
    }
    text += defaultValue;
    cursor += defaultValue.length;
    lastIndex = placeholderPattern.lastIndex;
  }
  text += replacement.slice(lastIndex);
  return {
    text,
    selectionFrom,
    selectionTo
  };
}
function expandSnippetVariables(pattern) {
  return pattern.replace(/\$\{([A-Z_]+)}/g, (_, name) => {
    var _a;
    return (_a = SNIPPET_VARIABLES[name]) != null ? _a : "";
  });
}
function getMathContext(textBeforeCursor) {
  let context = "text";
  for (let index = 0; index < textBeforeCursor.length; index += 1) {
    if (textBeforeCursor[index] !== "$" || isEscaped(textBeforeCursor, index)) {
      continue;
    }
    if (textBeforeCursor[index + 1] === "$") {
      context = context === "display" ? "text" : "display";
      index += 1;
      continue;
    }
    if (context !== "display") {
      context = context === "inline" ? "text" : "inline";
    }
  }
  return context;
}
function isEscaped(text, index) {
  let slashCount = 0;
  let cursor = index - 1;
  while (cursor >= 0 && text[cursor] === "\\") {
    slashCount += 1;
    cursor -= 1;
  }
  return slashCount % 2 === 1;
}

// src/main.ts
var DEFAULT_SETTINGS = {
  defaultTextWidth: 500,
  replaceSelectedText: true,
  renderInlineLatexOnInsert: true
};
var DOCUMENT_NODE_ID = 0;
var OPEN_INLINE_MATH_NODE_ID = 1;
var CLOSE_MATH_NODE_ID = 2;
var OPEN_DISPLAY_MATH_NODE_ID = 3;
var DOCUMENT_NODE = "Document";
var OPEN_INLINE_MATH_NODE = "formatting_formatting-math_formatting-math-begin_keyword_math";
var CLOSE_MATH_NODE = "formatting_formatting-math_formatting-math-end_keyword_math_math-";
var OPEN_DISPLAY_MATH_NODE = "formatting_formatting-math_formatting-math-begin_keyword_math_math-block";
var EXCALIDRAW_PLUGIN_ID = "obsidian-excalidraw-plugin";
var LATEX_SUITE_PLUGIN_ID = "obsidian-latex-suite";
var INLINE_FRAGMENT_GAP = 0;
var INLINE_ANCHOR_PADDING = 4;
var CONTAINER_PADDING_FALLBACK = 12;
var DEFAULT_FONT_FAMILY = 5;
var DEFAULT_LINE_HEIGHT = 1.25;
var DEFAULT_TEXT_STYLE = {
  strokeColor: "#1e1e1e",
  fontSize: 20,
  textAlign: "left"
};
var STROKE_OPTIONS = [
  { label: "Black", value: "#1e1e1e" },
  { label: "Red", value: "#e03131" },
  { label: "Green", value: "#2f9e44" },
  { label: "Blue", value: "#1971c2" },
  { label: "Orange", value: "#f08c00" },
  { label: "Purple", value: "#9c36b5" }
];
var FONT_SIZE_OPTIONS = [
  { label: "XS", value: 16 },
  { label: "S", value: 20 },
  { label: "M", value: 28 },
  { label: "L", value: 36 },
  { label: "XL", value: 48 }
];
var TEXT_ALIGN_OPTIONS = [
  { label: "Left", value: "left", icon: "align-left" },
  { label: "Center", value: "center", icon: "align-center" },
  { label: "Right", value: "right", icon: "align-right" }
];
var ExcalidrawLatexTextInputPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "insert-enhanced-text",
      name: "Insert enhanced text into Excalidraw",
      checkCallback: (checking) => {
        const view = getActiveExcalidrawView(this.app);
        if (!view) {
          return false;
        }
        if (!checking) {
          this.openInputModal(view);
        }
        return true;
      }
    });
    this.addCommand({
      id: "convert-selected-inline-latex",
      name: "Convert selected text to inline LaTeX",
      checkCallback: (checking) => {
        const view = getActiveExcalidrawView(this.app);
        if (!view) {
          return false;
        }
        if (!checking) {
          void this.convertSelectedInlineLatex(view);
        }
        return true;
      }
    });
    this.addSettingTab(new ExcalidrawLatexTextSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  openInputModal(view) {
    var _a, _b;
    const context = this.getInsertContext(view);
    if (!context) {
      return;
    }
    const initialText = (_b = (_a = context.selectedTextElement) == null ? void 0 : _a.text) != null ? _b : "";
    if (!context.latexSuiteAvailable) {
      new import_obsidian.Notice("LaTeX Suite is not available. Opening plain text input.");
    }
    new MixedLatexTextModal(this.app, {
      initialText,
      initialStyle: context.initialStyle,
      latexSuiteExtensions: getLatexSuiteExtensions(this.app),
      onSubmit: async (text, style) => {
        await this.insertIntoExcalidraw(text, style, context);
      }
    }).open();
  }
  getInsertContext(view) {
    const ea = getExcalidrawAutomate();
    if (!ea) {
      new import_obsidian.Notice("ExcalidrawAutomate is not available. Enable the Excalidraw plugin first.");
      return null;
    }
    if (!isPluginEnabled(this.app, EXCALIDRAW_PLUGIN_ID)) {
      new import_obsidian.Notice("Excalidraw plugin is not enabled.");
      return null;
    }
    if (!setExcalidrawAutomateView(ea, view)) {
      new import_obsidian.Notice("Could not target the active Excalidraw view.");
      return null;
    }
    const selectedTextElement = this.settings.replaceSelectedText ? getSingleSelectedTextElement(ea) : null;
    return {
      ea,
      view,
      selectedTextElement,
      initialStyle: getInitialTextStyle(ea, selectedTextElement),
      latexSuiteAvailable: getLatexSuiteExtensions(this.app).length > 0
    };
  }
  async insertIntoExcalidraw(text, style, context) {
    const normalizedText = text.trimEnd();
    if (!normalizedText) {
      new import_obsidian.Notice("Nothing to insert.");
      return;
    }
    if (this.settings.renderInlineLatexOnInsert && hasLatexFragment(parseInlineLatex(normalizedText))) {
      if (context.selectedTextElement && this.settings.replaceSelectedText) {
        const didReplace = await replaceTextElementWithInlineLatex(
          context.ea,
          context.view,
          context.selectedTextElement,
          normalizedText,
          style
        );
        if (didReplace) {
          new import_obsidian.Notice("Inserted inline LaTeX text.");
          return;
        }
        new import_obsidian.Notice("Could not convert the selected text. Creating new inline LaTeX text instead.");
      }
      const didInsertInline = await insertNewInlineLatexElements(
        context.ea,
        context.view,
        normalizedText,
        style,
        this.settings.defaultTextWidth
      );
      if (didInsertInline) {
        new import_obsidian.Notice("Inserted inline LaTeX text.");
        return;
      }
      new import_obsidian.Notice("Could not insert inline LaTeX. Creating a normal text element instead.");
    }
    if (context.selectedTextElement && this.settings.replaceSelectedText) {
      const didReplace = await replaceTextElement(
        context.ea,
        context.view,
        context.selectedTextElement,
        normalizedText,
        style
      );
      if (didReplace) {
        new import_obsidian.Notice("Updated Excalidraw text.");
        return;
      }
      new import_obsidian.Notice("Could not update the selected text. Creating a new text element instead.");
    }
    const didInsert = await insertNewTextElement(
      context.ea,
      context.view,
      normalizedText,
      style,
      this.settings.defaultTextWidth
    );
    if (!didInsert) {
      new import_obsidian.Notice("Could not insert text into the active Excalidraw view.");
      return;
    }
    new import_obsidian.Notice("Inserted Excalidraw text.");
  }
  async convertSelectedInlineLatex(view) {
    const context = this.getInsertContext(view);
    if (!context) {
      return;
    }
    const selectedTextElements = getSelectedTextElements(context.ea);
    if (selectedTextElements.length === 0) {
      new import_obsidian.Notice("Select one or more Excalidraw text elements first.");
      return;
    }
    const convertedCount = await convertTextElementsToInlineLatex(
      context.ea,
      context.view,
      selectedTextElements
    );
    if (convertedCount > 0) {
      new import_obsidian.Notice(
        convertedCount === 1 ? "Converted one text element to inline LaTeX." : `Converted ${convertedCount} text elements to inline LaTeX.`
      );
    }
  }
};
var MixedLatexTextModal = class extends import_obsidian.Modal {
  constructor(app, options) {
    super(app);
    this.options = options;
    this.editorView = null;
    this.textStyle = { ...options.initialStyle };
  }
  onOpen() {
    this.modalEl.addClass("excalidraw-latex-text-modal");
    this.titleEl.setText("Enhanced Excalidraw Text");
    this.contentEl.empty();
    const editorHost = this.contentEl.createDiv({
      cls: "excalidraw-latex-text-editor"
    });
    this.createStyleControls();
    const footer = this.contentEl.createDiv({
      cls: "excalidraw-latex-text-footer"
    });
    const cancelButton = footer.createEl("button", {
      text: "Cancel",
      type: "button"
    });
    cancelButton.addEventListener("click", () => this.close());
    const insertButton = footer.createEl("button", {
      text: "Insert",
      type: "button",
      cls: "mod-cta"
    });
    insertButton.addEventListener("click", () => {
      void this.submit();
    });
    this.editorView = new import_view2.EditorView({
      state: import_state.EditorState.create({
        doc: this.options.initialText,
        extensions: [
          import_view2.EditorView.lineWrapping,
          import_view2.EditorView.theme({
            "&": {
              minHeight: "44px"
            },
            ".cm-scroller": {
              fontFamily: "var(--font-text)",
              maxHeight: "320px",
              overflow: "auto"
            }
          }),
          import_view2.keymap.of([
            {
              key: "Shift-Enter",
              run: (view) => {
                insertEditorLineBreak(view);
                return true;
              }
            },
            {
              key: "Enter",
              run: (view) => {
                if (view.composing) {
                  return false;
                }
                void this.submit();
                return true;
              }
            },
            {
              key: "Mod-Enter",
              run: () => {
                void this.submit();
                return true;
              }
            },
            {
              key: "Escape",
              run: () => {
                this.close();
                return true;
              }
            }
          ]),
          createLatexSnippetExtension(latex_suite_snippets_default),
          latexSuiteMarkdownLanguage.extension,
          ...this.options.latexSuiteExtensions
        ]
      }),
      parent: editorHost
    });
    window.setTimeout(() => {
      var _a;
      return (_a = this.editorView) == null ? void 0 : _a.focus();
    }, 0);
  }
  createStyleControls() {
    const panel = this.contentEl.createDiv({
      cls: "excalidraw-latex-text-style-panel"
    });
    this.createStrokeControls(panel);
    this.createFontSizeControls(panel);
    this.createTextAlignControls(panel);
  }
  createStrokeControls(panel) {
    const group = createStyleSection(panel, "Stroke", "excalidraw-latex-text-swatches");
    for (const option of STROKE_OPTIONS) {
      const button = document.createElement("button");
      button.type = "button";
      button.className = "excalidraw-latex-text-swatch";
      button.dataset.value = option.value;
      button.setAttribute("aria-label", option.label);
      button.setAttribute("title", option.label);
      button.style.setProperty("--swatch-color", option.value);
      button.addEventListener("click", () => {
        var _a;
        this.textStyle.strokeColor = option.value;
        markSelectedStyleButton(group, option.value);
        (_a = this.editorView) == null ? void 0 : _a.focus();
      });
      group.appendChild(button);
    }
    markSelectedStyleButton(group, this.textStyle.strokeColor);
  }
  createFontSizeControls(panel) {
    const group = createStyleSection(panel, "Font size", "excalidraw-latex-text-segments");
    for (const option of FONT_SIZE_OPTIONS) {
      const button = document.createElement("button");
      button.type = "button";
      button.className = "excalidraw-latex-text-segment";
      button.dataset.value = String(option.value);
      button.textContent = option.label;
      button.addEventListener("click", () => {
        var _a;
        this.textStyle.fontSize = option.value;
        markSelectedStyleButton(group, String(option.value));
        (_a = this.editorView) == null ? void 0 : _a.focus();
      });
      group.appendChild(button);
    }
    markSelectedStyleButton(group, String(this.textStyle.fontSize));
  }
  createTextAlignControls(panel) {
    const group = createStyleSection(panel, "Text align", "excalidraw-latex-text-segments");
    for (const option of TEXT_ALIGN_OPTIONS) {
      const button = document.createElement("button");
      button.type = "button";
      button.className = "excalidraw-latex-text-segment excalidraw-latex-text-icon-segment";
      button.dataset.value = option.value;
      button.setAttribute("aria-label", option.label);
      button.setAttribute("title", option.label);
      (0, import_obsidian.setIcon)(button, option.icon);
      button.addEventListener("click", () => {
        var _a;
        this.textStyle.textAlign = option.value;
        markSelectedStyleButton(group, option.value);
        (_a = this.editorView) == null ? void 0 : _a.focus();
      });
      group.appendChild(button);
    }
    markSelectedStyleButton(group, this.textStyle.textAlign);
  }
  onClose() {
    var _a;
    (_a = this.editorView) == null ? void 0 : _a.destroy();
    this.editorView = null;
    this.contentEl.empty();
  }
  async submit() {
    if (!this.editorView) {
      return;
    }
    const text = this.editorView.state.doc.toString();
    const style = { ...this.textStyle };
    this.close();
    await this.options.onSubmit(text, style);
  }
};
var ExcalidrawLatexTextSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Default text width").setDesc("Width used when creating a new Excalidraw text element.").addText((text) => {
      text.setPlaceholder(String(DEFAULT_SETTINGS.defaultTextWidth)).setValue(String(this.plugin.settings.defaultTextWidth)).onChange(async (value) => {
        const parsed = Number(value);
        if (!Number.isFinite(parsed) || parsed <= 0) {
          return;
        }
        this.plugin.settings.defaultTextWidth = Math.round(parsed);
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Replace selected text").setDesc("When a single Excalidraw text element is selected, edit that element instead of creating a new one.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.replaceSelectedText).onChange(async (value) => {
        this.plugin.settings.replaceSelectedText = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Render inline LaTeX on insert").setDesc("When enabled, text inside math delimiters is inserted as Excalidraw LaTeX elements while surrounding text remains normal text.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.renderInlineLatexOnInsert).onChange(async (value) => {
        this.plugin.settings.renderInlineLatexOnInsert = value;
        await this.plugin.saveSettings();
      });
    });
  }
};
function insertEditorLineBreak(view) {
  const selection = view.state.selection.main;
  const anchor = selection.from + 1;
  view.dispatch({
    changes: {
      from: selection.from,
      to: selection.to,
      insert: "\n"
    },
    selection: {
      anchor
    },
    userEvent: "input"
  });
}
function createStyleSection(panel, label, groupClassName) {
  const section = panel.createDiv({
    cls: "excalidraw-latex-text-style-section"
  });
  section.createDiv({
    cls: "excalidraw-latex-text-style-label",
    text: label
  });
  return section.createDiv({
    cls: `excalidraw-latex-text-style-group ${groupClassName}`
  });
}
function markSelectedStyleButton(group, value) {
  for (const button of Array.from(group.querySelectorAll("button"))) {
    button.toggleClass("is-selected", button.dataset.value === value);
  }
}
function getActiveExcalidrawView(app) {
  var _a, _b, _c;
  const leaf = app.workspace.activeLeaf;
  if (!leaf) {
    return null;
  }
  const view = leaf.view;
  const viewType = (_b = (_a = view.getViewType) == null ? void 0 : _a.call(view).toLowerCase()) != null ? _b : "";
  if (viewType.includes("excalidraw")) {
    return view;
  }
  if ((_c = view.containerEl) == null ? void 0 : _c.querySelector(".excalidraw")) {
    return view;
  }
  return null;
}
var latexSuiteMarkdownNodeSet = new import_common.NodeSet([
  import_common.NodeType.define({
    id: DOCUMENT_NODE_ID,
    name: DOCUMENT_NODE,
    top: true
  }),
  import_common.NodeType.define({
    id: OPEN_INLINE_MATH_NODE_ID,
    name: OPEN_INLINE_MATH_NODE
  }),
  import_common.NodeType.define({
    id: CLOSE_MATH_NODE_ID,
    name: CLOSE_MATH_NODE
  }),
  import_common.NodeType.define({
    id: OPEN_DISPLAY_MATH_NODE_ID,
    name: OPEN_DISPLAY_MATH_NODE
  })
]);
var LatexSuiteMarkdownParser = class extends import_common.Parser {
  createParse(input, _fragments, _ranges) {
    const tree = buildLatexSuiteMarkdownTree(input.read(0, input.length));
    let isDone = false;
    return {
      parsedPos: input.length,
      stoppedAt: null,
      stopAt: () => void 0,
      advance: () => {
        if (isDone) {
          return tree;
        }
        isDone = true;
        return tree;
      }
    };
  }
};
var latexSuiteMarkdownLanguage = new import_language.Language(
  (0, import_language.defineLanguageFacet)(),
  new LatexSuiteMarkdownParser(),
  [],
  "markdown"
);
function buildLatexSuiteMarkdownTree(text) {
  const nodes = [];
  let index = 0;
  while (index < text.length) {
    const delimiter = findNextMathDelimiter(text, index);
    if (!delimiter) {
      break;
    }
    const close = findClosingMathDelimiter(
      text,
      delimiter.to,
      delimiter.marker
    );
    if (!close) {
      break;
    }
    nodes.push(delimiter.nodeId, delimiter.from, delimiter.to, 4);
    nodes.push(CLOSE_MATH_NODE_ID, close.from, close.to, 4);
    index = close.to;
  }
  const nodeCount = nodes.length / 4 + 1;
  nodes.push(DOCUMENT_NODE_ID, 0, text.length, nodeCount * 4);
  return import_common.Tree.build({
    buffer: nodes,
    nodeSet: latexSuiteMarkdownNodeSet,
    topID: DOCUMENT_NODE_ID,
    length: text.length
  });
}
function findNextMathDelimiter(text, from) {
  for (let index = from; index < text.length; index += 1) {
    if (text[index] !== "$" || isEscaped2(text, index)) {
      continue;
    }
    if (text[index + 1] === "$") {
      return {
        from: index,
        to: index + 2,
        marker: "$$",
        nodeId: OPEN_DISPLAY_MATH_NODE_ID
      };
    }
    return {
      from: index,
      to: index + 1,
      marker: "$",
      nodeId: OPEN_INLINE_MATH_NODE_ID
    };
  }
  return null;
}
function findClosingMathDelimiter(text, from, marker) {
  for (let index = from; index < text.length; index += 1) {
    if (text[index] !== "$" || isEscaped2(text, index)) {
      continue;
    }
    if (marker === "$$") {
      if (text[index + 1] === "$") {
        return {
          from: index,
          to: index + 2
        };
      }
      continue;
    }
    if (text[index + 1] !== "$") {
      return {
        from: index,
        to: index + 1
      };
    }
  }
  return null;
}
function isEscaped2(text, index) {
  let slashCount = 0;
  let cursor = index - 1;
  while (cursor >= 0 && text[cursor] === "\\") {
    slashCount += 1;
    cursor -= 1;
  }
  return slashCount % 2 === 1;
}
function getLatexSuiteExtensions(app) {
  const plugin = getPlugin(app, LATEX_SUITE_PLUGIN_ID);
  return Array.isArray(plugin == null ? void 0 : plugin.editorExtensions) ? plugin.editorExtensions : [];
}
function isPluginEnabled(app, pluginId) {
  return Boolean(getPlugin(app, pluginId));
}
function getPlugin(app, pluginId) {
  var _a, _b, _c;
  return (_c = (_b = (_a = app.plugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b[pluginId]) != null ? _c : null;
}
function getExcalidrawAutomate() {
  var _a, _b;
  const currentWindow = (_a = window.activeWindow) != null ? _a : window;
  const candidate = (_b = currentWindow.ExcalidrawAutomate) != null ? _b : window.ExcalidrawAutomate;
  return isObject(candidate) ? candidate : null;
}
function getSingleSelectedTextElement(ea) {
  var _a, _b, _c;
  try {
    const selected = (_b = (_a = ea.getViewSelectedElements) == null ? void 0 : _a.call(ea)) != null ? _b : [];
    if (selected.length === 1 && ((_c = selected[0]) == null ? void 0 : _c.type) === "text") {
      return selected[0];
    }
  } catch (error) {
    console.warn("Could not read selected Excalidraw elements.", error);
  }
  return null;
}
function getInitialTextStyle(ea, selectedTextElement) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n, _o;
  const appState = (_c = (_b = (_a = safeGetExcalidrawApi(ea)) == null ? void 0 : _a.getAppState) == null ? void 0 : _b.call(_a)) != null ? _c : {};
  const strokeColor = (_g = (_f = (_d = getStringValue(selectedTextElement == null ? void 0 : selectedTextElement.strokeColor)) != null ? _d : getStringValue(appState.currentItemStrokeColor)) != null ? _f : getStringValue((_e = ea.style) == null ? void 0 : _e.strokeColor)) != null ? _g : DEFAULT_TEXT_STYLE.strokeColor;
  const fontSize = getClosestFontSize(
    (_k = (_j = (_h = getNumberValue(selectedTextElement == null ? void 0 : selectedTextElement.fontSize)) != null ? _h : getNumberValue(appState.currentItemFontSize)) != null ? _j : getNumberValue((_i = ea.style) == null ? void 0 : _i.fontSize)) != null ? _k : DEFAULT_TEXT_STYLE.fontSize
  );
  const textAlign = (_o = (_n = (_l = getTextAlign(selectedTextElement == null ? void 0 : selectedTextElement.textAlign)) != null ? _l : getTextAlign(appState.currentItemTextAlign)) != null ? _n : getTextAlign((_m = ea.style) == null ? void 0 : _m.textAlign)) != null ? _o : DEFAULT_TEXT_STYLE.textAlign;
  return {
    strokeColor,
    fontSize,
    textAlign
  };
}
function getClosestFontSize(value) {
  return FONT_SIZE_OPTIONS.reduce((closest, option) => {
    return Math.abs(option.value - value) < Math.abs(closest - value) ? option.value : closest;
  }, FONT_SIZE_OPTIONS[0].value);
}
function getTextAlign(value) {
  return value === "left" || value === "center" || value === "right" ? value : null;
}
function getStringValue(value) {
  return typeof value === "string" && value ? value : null;
}
function getNumberValue(value) {
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}
var shouldJoinWithoutSpace = (before, after) => {
  const cjkOrFullWidth = /[\u3400-\u9fff\uff00-\uffef，。！？；：、（）【】《》“”‘’]/u;
  return cjkOrFullWidth.test(before) || cjkOrFullWidth.test(after);
};
function normalizeTextFragment(text) {
  return text.replace(/\\\$/g, "$").replace(/\r\n?/g, "\n").replace(/[ \t]*\n+[ \t]*/g, (match, offset, source) => {
    var _a, _b;
    const before = (_a = source[offset - 1]) != null ? _a : "";
    const after = (_b = source[offset + match.length]) != null ? _b : "";
    return shouldJoinWithoutSpace(before, after) ? "" : " ";
  }).replace(/[ \t]{2,}/g, " ");
}
function normalizeLatexFragment(latex) {
  return latex.replace(/\s+/g, " ").trim();
}
function parseInlineLatex(text) {
  const fragments = [];
  let buffer = "";
  let index = 0;
  const pushText = () => {
    const value = normalizeTextFragment(buffer);
    if (value) {
      fragments.push({ type: "text", value });
    }
    buffer = "";
  };
  while (index < text.length) {
    if (text[index] !== "$" || isEscaped2(text, index)) {
      buffer += text[index];
      index += 1;
      continue;
    }
    const delimiter = text[index + 1] === "$" ? "$$" : "$";
    const start = index + delimiter.length;
    let end = -1;
    for (let cursor = start; cursor < text.length; cursor += 1) {
      if (text.slice(cursor, cursor + delimiter.length) === delimiter && !isEscaped2(text, cursor)) {
        end = cursor;
        break;
      }
    }
    if (end === -1) {
      buffer += text[index];
      index += 1;
      continue;
    }
    pushText();
    const latex = normalizeLatexFragment(text.slice(start, end));
    if (latex) {
      fragments.push({ type: "latex", value: latex });
    }
    index = end + delimiter.length;
  }
  pushText();
  return fragments;
}
function hasLatexFragment(fragments) {
  return fragments.some((fragment) => fragment.type === "latex");
}
async function replaceTextElementWithInlineLatex(ea, view, element, text, style) {
  const convertedCount = await convertTextElementsToInlineLatex(
    ea,
    view,
    [element],
    /* @__PURE__ */ new Map([[element.id, { text, style }]])
  );
  return convertedCount > 0;
}
async function insertNewInlineLatexElements(ea, view, text, style, width) {
  var _a, _b, _c, _d, _e;
  if (!ea.addText || !ea.addLaTex || !ea.addElementsToView || !ea.getElement) {
    return false;
  }
  try {
    if (!setExcalidrawAutomateView(ea, view)) {
      return false;
    }
    const api = safeGetExcalidrawApi(ea);
    const appState = (_b = (_a = api == null ? void 0 : api.getAppState) == null ? void 0 : _a.call(api)) != null ? _b : {};
    (_c = ea.reset) == null ? void 0 : _c.call(ea);
    applyCurrentTextStyle(ea, appState);
    const renderStyle = getInlineTextStyle(ea, null, style);
    const point = (_e = (_d = ea.getViewCenterPosition) == null ? void 0 : _d.call(ea)) != null ? _e : getViewportCenterScenePoint(view, appState);
    const result = await insertInlineLinesInArea(
      ea,
      text,
      {
        x: point.x,
        y: point.y,
        width
      },
      renderStyle
    );
    if (result.ids.length === 0) {
      return false;
    }
    groupElements(ea, result.ids);
    const didAdd = await Promise.resolve(ea.addElementsToView(false, false, true));
    if (didAdd !== false) {
      selectElements(ea, result.ids);
      return true;
    }
    return false;
  } catch (error) {
    console.warn("Could not insert inline LaTeX through ExcalidrawAutomate.", error);
    return false;
  }
}
async function convertTextElementsToInlineLatex(ea, view, textElements, overrides = /* @__PURE__ */ new Map()) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i;
  if (!ea.addText || !ea.addLaTex || !ea.addElementsToView || !ea.deleteViewElements || !ea.getElement || !ea.getViewElements) {
    return 0;
  }
  if (!setExcalidrawAutomateView(ea, view)) {
    return 0;
  }
  (_a = ea.reset) == null ? void 0 : _a.call(ea);
  const convertedIds = [];
  const originalsToDelete = [];
  const bindingTargetIdsByOriginalId = /* @__PURE__ */ new Map();
  const connectedLinesByTextId = getConnectedLinesByElementId(
    ea,
    textElements.map((element) => element.id)
  );
  let skippedNoLatexCount = 0;
  let skippedMissingContainerCount = 0;
  for (const textElement of textElements) {
    const override = overrides.get(textElement.id);
    const sourceText = (_c = (_b = override == null ? void 0 : override.text) != null ? _b : textElement.text) != null ? _c : "";
    const fragments = parseInlineLatex(sourceText);
    if (!hasLatexFragment(fragments)) {
      skippedNoLatexCount += 1;
      continue;
    }
    const style = getInlineTextStyle(ea, textElement, override == null ? void 0 : override.style);
    const draftTextElement = (override == null ? void 0 : override.style) ? withUpdatedTextAndStyle(textElement, sourceText, override.style) : { ...textElement, text: sourceText };
    const connectedLines = (_d = connectedLinesByTextId.get(textElement.id)) != null ? _d : [];
    if (draftTextElement.containerId) {
      const containerElement = getViewElementById(ea, draftTextElement.containerId);
      if (!containerElement) {
        skippedMissingContainerCount += 1;
        continue;
      }
      const result2 = await insertInlineLinesInContainer(
        ea,
        draftTextElement,
        containerElement,
        style
      );
      if (result2.ids.length === 0) {
        continue;
      }
      (_e = ea.copyViewElementsToEAforEditing) == null ? void 0 : _e.call(ea, [containerElement]);
      const editableContainer = ea.getElement(containerElement.id);
      if (!editableContainer) {
        skippedMissingContainerCount += 1;
        continue;
      }
      addBoundLinesToElement(editableContainer, connectedLines);
      const ids2 = [editableContainer.id, ...result2.ids];
      groupElements(ea, ids2);
      if (connectedLines.length > 0) {
        bindingTargetIdsByOriginalId.set(textElement.id, editableContainer.id);
      }
      convertedIds.push(...ids2);
      originalsToDelete.push(textElement);
      continue;
    }
    const result = await insertInlineTextForElement(ea, draftTextElement, style);
    if (result.ids.length === 0) {
      continue;
    }
    let ids = result.ids;
    if (connectedLines.length > 0 && result.bounds) {
      const anchorId = createTransparentAnchor(ea, result.bounds, connectedLines);
      if (!anchorId) {
        continue;
      }
      bindingTargetIdsByOriginalId.set(textElement.id, anchorId);
      ids = [anchorId, ...result.ids];
    }
    groupElements(ea, ids);
    convertedIds.push(...ids);
    originalsToDelete.push(textElement);
  }
  if (bindingTargetIdsByOriginalId.size > 0) {
    const linesToEditById = /* @__PURE__ */ new Map();
    for (const connectedLines of connectedLinesByTextId.values()) {
      for (const { line } of connectedLines) {
        linesToEditById.set(line.id, line);
      }
    }
    (_f = ea.copyViewElementsToEAforEditing) == null ? void 0 : _f.call(ea, [...linesToEditById.values()]);
    for (const [oldId, targetId] of bindingTargetIdsByOriginalId.entries()) {
      for (const { line, side } of (_g = connectedLinesByTextId.get(oldId)) != null ? _g : []) {
        const editableLine = ea.getElement(line.id);
        if (!editableLine) {
          continue;
        }
        if (side === "start" && ((_h = editableLine.startBinding) == null ? void 0 : _h.elementId) === oldId) {
          editableLine.startBinding.elementId = targetId;
        }
        if (side === "end" && ((_i = editableLine.endBinding) == null ? void 0 : _i.elementId) === oldId) {
          editableLine.endBinding.elementId = targetId;
        }
      }
    }
  }
  if (originalsToDelete.length === 0) {
    showInlineConversionSkipNotices(skippedNoLatexCount, skippedMissingContainerCount);
    return 0;
  }
  ea.deleteViewElements(originalsToDelete);
  const didAdd = await Promise.resolve(ea.addElementsToView(false, false, true));
  if (didAdd === false) {
    return 0;
  }
  selectElements(ea, convertedIds);
  showInlineConversionSkipNotices(skippedNoLatexCount, skippedMissingContainerCount);
  return originalsToDelete.length;
}
function showInlineConversionSkipNotices(skippedNoLatexCount, skippedMissingContainerCount) {
  if (skippedNoLatexCount > 0) {
    new import_obsidian.Notice(
      skippedNoLatexCount === 1 ? "Selected text contains no inline LaTeX." : `${skippedNoLatexCount} selected text elements contain no inline LaTeX.`
    );
  }
  if (skippedMissingContainerCount > 0) {
    new import_obsidian.Notice(
      skippedMissingContainerCount === 1 ? "Skipped one text element because its container was not found." : `Skipped ${skippedMissingContainerCount} text elements because their containers were not found.`
    );
  }
}
async function insertInlineTextForElement(ea, textElement, style) {
  var _a;
  return insertInlineLinesInArea(
    ea,
    (_a = textElement.text) != null ? _a : "",
    {
      x: toNumber(textElement.x, 0),
      y: toNumber(textElement.y, 0),
      width: Math.max(style.fontSize, toNumber(textElement.width, style.fontSize))
    },
    style
  );
}
async function insertInlineLinesInContainer(ea, textElement, containerElement, style) {
  var _a, _b;
  const lines = splitTextLines((_a = textElement.text) != null ? _a : "");
  const area = getContainerTextArea(textElement, containerElement, style);
  const startY = getContainerContentTopY(area, lines.length, style);
  return insertInlineLinesInArea(
    ea,
    (_b = textElement.text) != null ? _b : "",
    {
      ...area,
      y: startY
    },
    style
  );
}
async function insertInlineLinesInArea(ea, text, area, style) {
  const lines = splitTextLines(text);
  const lineHeight = getLineHeight(style);
  const ids = [];
  let bounds = null;
  for (let index = 0; index < lines.length; index += 1) {
    const fragments = parseInlineLatex(lines[index]);
    if (fragments.length === 0) {
      continue;
    }
    const lineResult = await insertInlineFragments(
      ea,
      fragments,
      {
        x: area.x,
        y: area.y + index * lineHeight,
        centerY: area.y + index * lineHeight + lineHeight / 2,
        align: "left"
      },
      style
    );
    if (lineResult.ids.length === 0 || !lineResult.bounds) {
      continue;
    }
    const lineX = getAlignedLineX(area, lineResult.bounds.width, style.textAlign);
    const dx = lineX - lineResult.bounds.x;
    if (dx !== 0) {
      moveElementsBy(ea, lineResult.ids, dx, 0);
      lineResult.bounds.x += dx;
    }
    ids.push(...lineResult.ids);
    bounds = mergeBounds(bounds, lineResult.bounds);
  }
  return { ids, bounds };
}
async function insertInlineFragments(ea, fragments, anchor, style) {
  var _a;
  if (!ea.addText || !ea.addLaTex || !ea.getElement) {
    return { ids: [], bounds: null };
  }
  applyInlineTextStyle(ea, style);
  const latexScale = Math.max(0.6, style.fontSize / 20);
  const ids = [];
  for (const fragment of fragments) {
    if (fragment.type === "latex") {
      const id2 = await Promise.resolve(ea.addLaTex(0, 0, fragment.value, latexScale, latexScale));
      if (id2) {
        ids.push(id2);
      }
      continue;
    }
    const id = ea.addText(0, 0, fragment.value);
    if (id) {
      ids.push(id);
    }
  }
  const elements = ids.map((id) => {
    var _a2;
    return (_a2 = ea.getElement) == null ? void 0 : _a2.call(ea, id);
  }).filter(isExcalidrawElement);
  if (elements.length === 0) {
    return { ids: [], bounds: null };
  }
  const totalWidth = elements.reduce((sum, element) => sum + toNumber(element.width, 0), 0) + INLINE_FRAGMENT_GAP * Math.max(0, elements.length - 1);
  const maxHeight = Math.max(...elements.map((element) => toNumber(element.height, style.fontSize)));
  const startX = anchor.align === "center" ? anchor.x - totalWidth / 2 : anchor.align === "right" ? anchor.x - totalWidth : anchor.x;
  const centerY = (_a = anchor.centerY) != null ? _a : anchor.y + maxHeight / 2;
  const topY = centerY - maxHeight / 2;
  let cursorX = startX;
  for (const element of elements) {
    element.x = cursorX;
    element.y = topY + (maxHeight - toNumber(element.height, style.fontSize)) / 2;
    cursorX += toNumber(element.width, 0) + INLINE_FRAGMENT_GAP;
  }
  return { ids, bounds: getBoundingBoxByIds(ea, ids) };
}
function splitTextLines(text) {
  return text.replace(/\r\n?/g, "\n").split("\n");
}
function getInlineTextStyle(ea, element, override) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n, _o, _p, _q, _r, _s, _t, _u, _v, _w, _x, _y, _z;
  const appState = (_c = (_b = (_a = safeGetExcalidrawApi(ea)) == null ? void 0 : _a.getAppState) == null ? void 0 : _b.call(_a)) != null ? _c : {};
  return {
    strokeColor: (_h = (_g = (_e = (_d = override == null ? void 0 : override.strokeColor) != null ? _d : getStringValue(element == null ? void 0 : element.strokeColor)) != null ? _e : getStringValue(appState.currentItemStrokeColor)) != null ? _g : getStringValue((_f = ea.style) == null ? void 0 : _f.strokeColor)) != null ? _h : DEFAULT_TEXT_STYLE.strokeColor,
    fontFamily: (_l = (_k = (_i = getNumberValue(element == null ? void 0 : element.fontFamily)) != null ? _i : getNumberValue(appState.currentItemFontFamily)) != null ? _k : getNumberValue((_j = ea.style) == null ? void 0 : _j.fontFamily)) != null ? _l : DEFAULT_FONT_FAMILY,
    fontSize: (_q = (_p = (_n = (_m = override == null ? void 0 : override.fontSize) != null ? _m : getNumberValue(element == null ? void 0 : element.fontSize)) != null ? _n : getNumberValue(appState.currentItemFontSize)) != null ? _p : getNumberValue((_o = ea.style) == null ? void 0 : _o.fontSize)) != null ? _q : DEFAULT_TEXT_STYLE.fontSize,
    textAlign: (_v = (_u = (_s = (_r = override == null ? void 0 : override.textAlign) != null ? _r : getTextAlign(element == null ? void 0 : element.textAlign)) != null ? _s : getTextAlign(appState.currentItemTextAlign)) != null ? _u : getTextAlign((_t = ea.style) == null ? void 0 : _t.textAlign)) != null ? _v : DEFAULT_TEXT_STYLE.textAlign,
    verticalAlign: (_x = (_w = getStringValue(element == null ? void 0 : element.verticalAlign)) != null ? _w : getStringValue(appState.currentItemVerticalAlign)) != null ? _x : "top",
    lineHeight: (_z = (_y = getNumberValue(element == null ? void 0 : element.lineHeight)) != null ? _y : getNumberValue(appState.currentItemLineHeight)) != null ? _z : DEFAULT_LINE_HEIGHT
  };
}
function applyInlineTextStyle(ea, style) {
  if (!ea.style) {
    return;
  }
  ea.style.strokeColor = style.strokeColor;
  ea.style.fontFamily = style.fontFamily;
  ea.style.fontSize = style.fontSize;
  ea.style.textAlign = style.textAlign;
}
function getLineHeight(style) {
  return style.fontSize * (style.lineHeight > 0 ? style.lineHeight : DEFAULT_LINE_HEIGHT);
}
function getAlignedLineX(area, lineWidth, textAlign) {
  if (textAlign === "center") {
    return area.x + (area.width - lineWidth) / 2;
  }
  if (textAlign === "right") {
    return area.x + area.width - lineWidth;
  }
  return area.x;
}
function getContainerTextArea(textElement, containerElement, style) {
  const paddingX = Math.max(CONTAINER_PADDING_FALLBACK, style.fontSize * 0.5);
  const paddingY = Math.max(CONTAINER_PADDING_FALLBACK, style.fontSize * 0.35);
  const fallback = {
    x: toNumber(containerElement.x, 0) + paddingX,
    y: toNumber(containerElement.y, 0) + paddingY,
    width: Math.max(style.fontSize, toNumber(containerElement.width, style.fontSize) - 2 * paddingX),
    height: Math.max(style.fontSize, toNumber(containerElement.height, style.fontSize) - 2 * paddingY)
  };
  return {
    x: Number.isFinite(textElement.x) ? toNumber(textElement.x, fallback.x) : fallback.x,
    y: Number.isFinite(textElement.y) ? toNumber(textElement.y, fallback.y) : fallback.y,
    width: Number.isFinite(textElement.width) && toNumber(textElement.width, 0) > 0 ? toNumber(textElement.width, fallback.width) : fallback.width,
    height: Number.isFinite(textElement.height) && toNumber(textElement.height, 0) > 0 ? toNumber(textElement.height, fallback.height) : fallback.height
  };
}
function getContainerContentTopY(area, lineCount, style) {
  const lineHeight = getLineHeight(style);
  const contentHeight = Math.max(lineHeight, lineCount * lineHeight);
  if (style.verticalAlign === "middle" && area.height > contentHeight) {
    return area.y + (area.height - contentHeight) / 2;
  }
  if (style.verticalAlign === "bottom" && area.height > contentHeight) {
    return area.y + area.height - contentHeight;
  }
  return area.y;
}
function getBoundingBoxByIds(ea, ids) {
  const elements = ids.map((id) => {
    var _a;
    return (_a = ea.getElement) == null ? void 0 : _a.call(ea, id);
  }).filter(isExcalidrawElement);
  if (elements.length === 0) {
    return null;
  }
  const minX = Math.min(...elements.map((element) => toNumber(element.x, 0)));
  const minY = Math.min(...elements.map((element) => toNumber(element.y, 0)));
  const maxX = Math.max(...elements.map((element) => toNumber(element.x, 0) + toNumber(element.width, 0)));
  const maxY = Math.max(...elements.map((element) => toNumber(element.y, 0) + toNumber(element.height, 0)));
  return {
    x: minX,
    y: minY,
    width: maxX - minX,
    height: maxY - minY
  };
}
function mergeBounds(first, second) {
  if (!first) {
    return second;
  }
  if (!second) {
    return first;
  }
  const minX = Math.min(first.x, second.x);
  const minY = Math.min(first.y, second.y);
  const maxX = Math.max(first.x + first.width, second.x + second.width);
  const maxY = Math.max(first.y + first.height, second.y + second.height);
  return {
    x: minX,
    y: minY,
    width: maxX - minX,
    height: maxY - minY
  };
}
function moveElementsBy(ea, ids, dx, dy) {
  var _a;
  for (const id of ids) {
    const element = (_a = ea.getElement) == null ? void 0 : _a.call(ea, id);
    if (!element) {
      continue;
    }
    element.x = toNumber(element.x, 0) + dx;
    element.y = toNumber(element.y, 0) + dy;
  }
}
function getViewElementById(ea, id) {
  var _a, _b;
  return (_b = (_a = ea.getViewElements) == null ? void 0 : _a.call(ea).find((element) => element.id === id && !element.isDeleted)) != null ? _b : null;
}
function getConnectedLinesByElementId(ea, elementIds) {
  var _a, _b, _c, _d, _e, _f;
  const selectedIds = new Set(elementIds);
  const connected = /* @__PURE__ */ new Map();
  for (const element of (_b = (_a = ea.getViewElements) == null ? void 0 : _a.call(ea)) != null ? _b : []) {
    if (element.type !== "arrow" && element.type !== "line") {
      continue;
    }
    const startId = (_c = element.startBinding) == null ? void 0 : _c.elementId;
    const endId = (_d = element.endBinding) == null ? void 0 : _d.elementId;
    if (startId && selectedIds.has(startId)) {
      if (!connected.has(startId)) {
        connected.set(startId, []);
      }
      (_e = connected.get(startId)) == null ? void 0 : _e.push({ line: element, side: "start" });
    }
    if (endId && selectedIds.has(endId)) {
      if (!connected.has(endId)) {
        connected.set(endId, []);
      }
      (_f = connected.get(endId)) == null ? void 0 : _f.push({ line: element, side: "end" });
    }
  }
  return connected;
}
function createTransparentAnchor(ea, bounds, connectedLines) {
  if (!ea.addRect || !ea.getElement) {
    return null;
  }
  if (ea.style) {
    ea.style.strokeColor = "transparent";
    ea.style.backgroundColor = "transparent";
    ea.style.fillStyle = "solid";
  }
  const anchorId = ea.addRect(
    bounds.x - INLINE_ANCHOR_PADDING,
    bounds.y - INLINE_ANCHOR_PADDING,
    bounds.width + 2 * INLINE_ANCHOR_PADDING,
    bounds.height + 2 * INLINE_ANCHOR_PADDING
  );
  const anchor = anchorId ? ea.getElement(anchorId) : null;
  if (!anchor) {
    return null;
  }
  anchor.strokeColor = "transparent";
  anchor.backgroundColor = "transparent";
  anchor.fillStyle = "solid";
  anchor.strokeWidth = 1;
  anchor.roughness = 0;
  anchor.opacity = 100;
  anchor.boundElements = connectedLines.map(({ line }) => ({ type: "arrow", id: line.id }));
  return anchorId;
}
function addBoundLinesToElement(element, connectedLines) {
  const boundElements = Array.isArray(element.boundElements) ? element.boundElements.filter((boundElement) => boundElement.type !== "text") : [];
  const seen = new Set(boundElements.map((boundElement) => `${boundElement.type}:${boundElement.id}`));
  for (const { line } of connectedLines) {
    const key = `arrow:${line.id}`;
    if (!seen.has(key)) {
      boundElements.push({ type: "arrow", id: line.id });
      seen.add(key);
    }
  }
  element.boundElements = boundElements.length > 0 ? boundElements : null;
}
function getSelectedTextElements(ea) {
  var _a, _b, _c;
  const textElementsById = /* @__PURE__ */ new Map();
  const addTextElement = (element) => {
    if ((element == null ? void 0 : element.type) === "text" && !element.isDeleted) {
      textElementsById.set(element.id, element);
    }
  };
  try {
    for (const element of (_b = (_a = ea.getViewSelectedElements) == null ? void 0 : _a.call(ea)) != null ? _b : []) {
      addTextElement(element);
      for (const boundElement of (_c = element.boundElements) != null ? _c : []) {
        if (boundElement.type === "text") {
          addTextElement(getViewElementById(ea, boundElement.id));
        }
      }
    }
  } catch (error) {
    console.warn("Could not read selected Excalidraw text elements.", error);
  }
  return [...textElementsById.values()];
}
function groupElements(ea, ids) {
  var _a;
  if (ids.length > 1) {
    (_a = ea.addToGroup) == null ? void 0 : _a.call(ea, ids);
  }
}
function selectElements(ea, ids) {
  var _a;
  if (ids.length > 0) {
    (_a = ea.selectElementsInView) == null ? void 0 : _a.call(ea, ids);
  }
}
async function replaceTextElement(ea, view, element, text, style) {
  if (!setExcalidrawAutomateView(ea, view)) {
    return false;
  }
  const updated = withUpdatedTextAndStyle(element, text, style);
  if (ea.copyViewElementsToEAforEditing && ea.addElementsToView) {
    try {
      ea.copyViewElementsToEAforEditing([updated]);
      return await Promise.resolve(ea.addElementsToView(false));
    } catch (error) {
      console.warn("Could not update text through ExcalidrawAutomate.", error);
    }
  }
  const api = safeGetExcalidrawApi(ea);
  if (!(api == null ? void 0 : api.getSceneElements) || !api.updateScene) {
    return false;
  }
  try {
    const elements = api.getSceneElements().map((sceneElement) => {
      return sceneElement.id === element.id ? withUpdatedTextAndStyle(sceneElement, text, style) : sceneElement;
    });
    api.updateScene({
      elements,
      commitToHistory: true
    });
    return true;
  } catch (error) {
    console.warn("Could not update text through Excalidraw API.", error);
    return false;
  }
}
async function insertNewTextElement(ea, view, text, style, width) {
  var _a, _b, _c, _d, _e;
  if (!ea.addText || !ea.addElementsToView) {
    return false;
  }
  try {
    if (!setExcalidrawAutomateView(ea, view)) {
      return false;
    }
    const api = safeGetExcalidrawApi(ea);
    const appState = (_b = (_a = api == null ? void 0 : api.getAppState) == null ? void 0 : _a.call(api)) != null ? _b : {};
    (_c = ea.reset) == null ? void 0 : _c.call(ea);
    applyCurrentTextStyle(ea, appState);
    applySelectedTextStyle(ea, style);
    const point = (_e = (_d = ea.getViewCenterPosition) == null ? void 0 : _d.call(ea)) != null ? _e : getViewportCenterScenePoint(view, appState);
    const id = ea.addText(point.x, point.y, text, {
      width,
      textAlign: style.textAlign
    });
    if (!id) {
      return false;
    }
    return await Promise.resolve(ea.addElementsToView(false));
  } catch (error) {
    console.warn("Could not insert text through ExcalidrawAutomate.", error);
    return false;
  }
}
function setExcalidrawAutomateView(ea, view) {
  var _a, _b;
  if (!ea.setView) {
    return true;
  }
  try {
    const target = (_b = (_a = ea.setView(view, false)) != null ? _a : ea.setView("active", false)) != null ? _b : ea.setView("auto", false);
    return Boolean(target);
  } catch (error) {
    console.warn("Could not set ExcalidrawAutomate target view.", error);
    return false;
  }
}
function withUpdatedTextAndStyle(element, text, style) {
  const next = {
    ...element,
    text,
    strokeColor: style.strokeColor,
    fontSize: style.fontSize,
    textAlign: style.textAlign
  };
  if ("rawText" in next) {
    next.rawText = text;
  }
  if ("originalText" in next) {
    next.originalText = text;
  }
  return next;
}
function safeGetExcalidrawApi(ea) {
  var _a, _b;
  try {
    return (_b = (_a = ea.getExcalidrawAPI) == null ? void 0 : _a.call(ea)) != null ? _b : null;
  } catch (error) {
    console.warn("Could not access Excalidraw API.", error);
    return null;
  }
}
function applyCurrentTextStyle(ea, appState) {
  if (!ea.style) {
    return;
  }
  copyStyleValue(appState, "currentItemStrokeColor", ea.style, "strokeColor");
  copyStyleValue(appState, "currentItemBackgroundColor", ea.style, "backgroundColor");
  copyStyleValue(appState, "currentItemFontFamily", ea.style, "fontFamily");
  copyStyleValue(appState, "currentItemFontSize", ea.style, "fontSize");
  copyStyleValue(appState, "currentItemTextAlign", ea.style, "textAlign");
  copyStyleValue(appState, "currentItemOpacity", ea.style, "opacity");
  copyStyleValue(appState, "currentItemRoughness", ea.style, "roughness");
}
function applySelectedTextStyle(ea, style) {
  if (!ea.style) {
    return;
  }
  ea.style.strokeColor = style.strokeColor;
  ea.style.fontSize = style.fontSize;
  ea.style.textAlign = style.textAlign;
}
function copyStyleValue(source, sourceKey, target, targetKey) {
  const value = source[sourceKey];
  if (value !== void 0 && value !== null) {
    target[targetKey] = value;
  }
}
function getViewportCenterScenePoint(view, appState) {
  var _a, _b, _c;
  const containerEl = isObject(view) && isHTMLElementLike(view.containerEl) ? view.containerEl : null;
  const drawingEl = containerEl == null ? void 0 : containerEl.querySelector(".excalidraw");
  const rect = (_a = drawingEl != null ? drawingEl : containerEl) == null ? void 0 : _a.getBoundingClientRect();
  const width = (_b = rect == null ? void 0 : rect.width) != null ? _b : window.innerWidth;
  const height = (_c = rect == null ? void 0 : rect.height) != null ? _c : window.innerHeight;
  const scrollX = toNumber(appState.scrollX, 0);
  const scrollY = toNumber(appState.scrollY, 0);
  const zoom = getZoomValue(appState.zoom);
  return {
    x: Math.round((width / 2 - scrollX) / zoom),
    y: Math.round((height / 2 - scrollY) / zoom)
  };
}
function getZoomValue(value) {
  const zoom = isObject(value) ? toNumber(value.value, 1) : toNumber(value, 1);
  return zoom > 0 ? zoom : 1;
}
function toNumber(value, fallback) {
  return typeof value === "number" && Number.isFinite(value) ? value : fallback;
}
function isObject(value) {
  return typeof value === "object" && value !== null;
}
function isExcalidrawElement(value) {
  return isObject(value) && typeof value.id === "string" && typeof value.type === "string";
}
function isHTMLElementLike(value) {
  return value instanceof HTMLElement || isObject(value) && typeof value.querySelector === "function" && typeof value.getBoundingClientRect === "function";
}
