/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ExcalidrawLatexTextInputPlugin
});
module.exports = __toCommonJS(main_exports);
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
var import_language = require("@codemirror/language");
var import_common = require("@lezer/common");
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  defaultTextWidth: 500,
  replaceSelectedText: true
};
var DOCUMENT_NODE_ID = 0;
var OPEN_INLINE_MATH_NODE_ID = 1;
var CLOSE_MATH_NODE_ID = 2;
var OPEN_DISPLAY_MATH_NODE_ID = 3;
var DOCUMENT_NODE = "Document";
var OPEN_INLINE_MATH_NODE = "formatting_formatting-math_formatting-math-begin_keyword_math";
var CLOSE_MATH_NODE = "formatting_formatting-math_formatting-math-end_keyword_math_math-";
var OPEN_DISPLAY_MATH_NODE = "formatting_formatting-math_formatting-math-begin_keyword_math_math-block";
var EXCALIDRAW_PLUGIN_ID = "obsidian-excalidraw-plugin";
var LATEX_SUITE_PLUGIN_ID = "obsidian-latex-suite";
var ExcalidrawLatexTextInputPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "insert-enhanced-text",
      name: "Insert enhanced text into Excalidraw",
      checkCallback: (checking) => {
        const view = getActiveExcalidrawView(this.app);
        if (!view) {
          return false;
        }
        if (!checking) {
          this.openInputModal(view);
        }
        return true;
      }
    });
    this.addSettingTab(new ExcalidrawLatexTextSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  openInputModal(view) {
    var _a, _b;
    const context = this.getInsertContext(view);
    if (!context) {
      return;
    }
    const initialText = (_b = (_a = context.selectedTextElement) == null ? void 0 : _a.text) != null ? _b : "";
    if (!context.latexSuiteAvailable) {
      new import_obsidian.Notice("LaTeX Suite is not available. Opening plain text input.");
    }
    new MixedLatexTextModal(this.app, {
      initialText,
      latexSuiteExtensions: getLatexSuiteExtensions(this.app),
      onSubmit: async (text) => {
        await this.insertIntoExcalidraw(text, context);
      }
    }).open();
  }
  getInsertContext(view) {
    const ea = getExcalidrawAutomate();
    if (!ea) {
      new import_obsidian.Notice("ExcalidrawAutomate is not available. Enable the Excalidraw plugin first.");
      return null;
    }
    if (!isPluginEnabled(this.app, EXCALIDRAW_PLUGIN_ID)) {
      new import_obsidian.Notice("Excalidraw plugin is not enabled.");
      return null;
    }
    const selectedTextElement = this.settings.replaceSelectedText ? getSingleSelectedTextElement(ea) : null;
    return {
      ea,
      view,
      selectedTextElement,
      latexSuiteAvailable: getLatexSuiteExtensions(this.app).length > 0
    };
  }
  async insertIntoExcalidraw(text, context) {
    const normalizedText = text.trimEnd();
    if (!normalizedText) {
      new import_obsidian.Notice("Nothing to insert.");
      return;
    }
    if (context.selectedTextElement && this.settings.replaceSelectedText) {
      const didReplace = await replaceTextElement(context.ea, context.selectedTextElement, normalizedText);
      if (didReplace) {
        return;
      }
      new import_obsidian.Notice("Could not update the selected text. Creating a new text element instead.");
    }
    const didInsert = await insertNewTextElement(
      context.ea,
      context.view,
      normalizedText,
      this.settings.defaultTextWidth
    );
    if (!didInsert) {
      new import_obsidian.Notice("Could not insert text into the active Excalidraw view.");
    }
  }
};
var MixedLatexTextModal = class extends import_obsidian.Modal {
  constructor(app, options) {
    super(app);
    this.options = options;
    this.editorView = null;
  }
  onOpen() {
    this.modalEl.addClass("excalidraw-latex-text-modal");
    this.titleEl.setText("Enhanced Excalidraw Text");
    this.contentEl.empty();
    const editorHost = this.contentEl.createDiv({
      cls: "excalidraw-latex-text-editor"
    });
    const footer = this.contentEl.createDiv({
      cls: "excalidraw-latex-text-footer"
    });
    const cancelButton = footer.createEl("button", {
      text: "Cancel",
      type: "button"
    });
    cancelButton.addEventListener("click", () => this.close());
    const insertButton = footer.createEl("button", {
      text: "Insert",
      type: "button",
      cls: "mod-cta"
    });
    insertButton.addEventListener("click", () => {
      void this.submit();
    });
    this.editorView = new import_view.EditorView({
      state: import_state.EditorState.create({
        doc: this.options.initialText,
        extensions: [
          import_view.EditorView.lineWrapping,
          import_view.EditorView.theme({
            "&": {
              minHeight: "260px"
            },
            ".cm-scroller": {
              fontFamily: "var(--font-text)"
            }
          }),
          import_view.keymap.of([
            {
              key: "Mod-Enter",
              run: () => {
                void this.submit();
                return true;
              }
            },
            {
              key: "Escape",
              run: () => {
                this.close();
                return true;
              }
            }
          ]),
          latexSuiteMarkdownLanguage.extension,
          ...this.options.latexSuiteExtensions
        ]
      }),
      parent: editorHost
    });
    window.setTimeout(() => {
      var _a;
      return (_a = this.editorView) == null ? void 0 : _a.focus();
    }, 0);
  }
  onClose() {
    var _a;
    (_a = this.editorView) == null ? void 0 : _a.destroy();
    this.editorView = null;
    this.contentEl.empty();
  }
  async submit() {
    if (!this.editorView) {
      return;
    }
    const text = this.editorView.state.doc.toString();
    this.close();
    await this.options.onSubmit(text);
  }
};
var ExcalidrawLatexTextSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Default text width").setDesc("Width used when creating a new Excalidraw text element.").addText((text) => {
      text.setPlaceholder(String(DEFAULT_SETTINGS.defaultTextWidth)).setValue(String(this.plugin.settings.defaultTextWidth)).onChange(async (value) => {
        const parsed = Number(value);
        if (!Number.isFinite(parsed) || parsed <= 0) {
          return;
        }
        this.plugin.settings.defaultTextWidth = Math.round(parsed);
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Replace selected text").setDesc("When a single Excalidraw text element is selected, edit that element instead of creating a new one.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.replaceSelectedText).onChange(async (value) => {
        this.plugin.settings.replaceSelectedText = value;
        await this.plugin.saveSettings();
      });
    });
  }
};
function getActiveExcalidrawView(app) {
  var _a, _b, _c;
  const leaf = app.workspace.activeLeaf;
  if (!leaf) {
    return null;
  }
  const view = leaf.view;
  const viewType = (_b = (_a = view.getViewType) == null ? void 0 : _a.call(view).toLowerCase()) != null ? _b : "";
  if (viewType.includes("excalidraw")) {
    return view;
  }
  if ((_c = view.containerEl) == null ? void 0 : _c.querySelector(".excalidraw")) {
    return view;
  }
  return null;
}
var latexSuiteMarkdownNodeSet = new import_common.NodeSet([
  import_common.NodeType.define({
    id: DOCUMENT_NODE_ID,
    name: DOCUMENT_NODE,
    top: true
  }),
  import_common.NodeType.define({
    id: OPEN_INLINE_MATH_NODE_ID,
    name: OPEN_INLINE_MATH_NODE
  }),
  import_common.NodeType.define({
    id: CLOSE_MATH_NODE_ID,
    name: CLOSE_MATH_NODE
  }),
  import_common.NodeType.define({
    id: OPEN_DISPLAY_MATH_NODE_ID,
    name: OPEN_DISPLAY_MATH_NODE
  })
]);
var LatexSuiteMarkdownParser = class extends import_common.Parser {
  createParse(input, _fragments, _ranges) {
    const tree = buildLatexSuiteMarkdownTree(input.read(0, input.length));
    let isDone = false;
    return {
      parsedPos: input.length,
      stoppedAt: null,
      stopAt: () => void 0,
      advance: () => {
        if (isDone) {
          return tree;
        }
        isDone = true;
        return tree;
      }
    };
  }
};
var latexSuiteMarkdownLanguage = new import_language.Language(
  (0, import_language.defineLanguageFacet)(),
  new LatexSuiteMarkdownParser(),
  [],
  "markdown"
);
function buildLatexSuiteMarkdownTree(text) {
  const nodes = [];
  let index = 0;
  while (index < text.length) {
    const delimiter = findNextMathDelimiter(text, index);
    if (!delimiter) {
      break;
    }
    const close = findClosingMathDelimiter(
      text,
      delimiter.to,
      delimiter.marker
    );
    if (!close) {
      break;
    }
    nodes.push(delimiter.nodeId, delimiter.from, delimiter.to, 4);
    nodes.push(CLOSE_MATH_NODE_ID, close.from, close.to, 4);
    index = close.to;
  }
  const nodeCount = nodes.length / 4 + 1;
  nodes.push(DOCUMENT_NODE_ID, 0, text.length, nodeCount * 4);
  return import_common.Tree.build({
    buffer: nodes,
    nodeSet: latexSuiteMarkdownNodeSet,
    topID: DOCUMENT_NODE_ID,
    length: text.length
  });
}
function findNextMathDelimiter(text, from) {
  for (let index = from; index < text.length; index += 1) {
    if (text[index] !== "$" || isEscaped(text, index)) {
      continue;
    }
    if (text[index + 1] === "$") {
      return {
        from: index,
        to: index + 2,
        marker: "$$",
        nodeId: OPEN_DISPLAY_MATH_NODE_ID
      };
    }
    return {
      from: index,
      to: index + 1,
      marker: "$",
      nodeId: OPEN_INLINE_MATH_NODE_ID
    };
  }
  return null;
}
function findClosingMathDelimiter(text, from, marker) {
  for (let index = from; index < text.length; index += 1) {
    if (text[index] !== "$" || isEscaped(text, index)) {
      continue;
    }
    if (marker === "$$") {
      if (text[index + 1] === "$") {
        return {
          from: index,
          to: index + 2
        };
      }
      continue;
    }
    if (text[index + 1] !== "$") {
      return {
        from: index,
        to: index + 1
      };
    }
  }
  return null;
}
function isEscaped(text, index) {
  let slashCount = 0;
  let cursor = index - 1;
  while (cursor >= 0 && text[cursor] === "\\") {
    slashCount += 1;
    cursor -= 1;
  }
  return slashCount % 2 === 1;
}
function getLatexSuiteExtensions(app) {
  const plugin = getPlugin(app, LATEX_SUITE_PLUGIN_ID);
  return Array.isArray(plugin == null ? void 0 : plugin.editorExtensions) ? plugin.editorExtensions : [];
}
function isPluginEnabled(app, pluginId) {
  return Boolean(getPlugin(app, pluginId));
}
function getPlugin(app, pluginId) {
  var _a, _b, _c;
  return (_c = (_b = (_a = app.plugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b[pluginId]) != null ? _c : null;
}
function getExcalidrawAutomate() {
  var _a, _b;
  const currentWindow = (_a = window.activeWindow) != null ? _a : window;
  const candidate = (_b = currentWindow.ExcalidrawAutomate) != null ? _b : window.ExcalidrawAutomate;
  return isObject(candidate) ? candidate : null;
}
function getSingleSelectedTextElement(ea) {
  var _a, _b, _c;
  try {
    const selected = (_b = (_a = ea.getViewSelectedElements) == null ? void 0 : _a.call(ea)) != null ? _b : [];
    if (selected.length === 1 && ((_c = selected[0]) == null ? void 0 : _c.type) === "text") {
      return selected[0];
    }
  } catch (error) {
    console.warn("Could not read selected Excalidraw elements.", error);
  }
  return null;
}
async function replaceTextElement(ea, element, text) {
  const updated = withUpdatedText(element, text);
  if (ea.copyViewElementsToEAforEditing && ea.addElementsToView) {
    try {
      ea.copyViewElementsToEAforEditing([updated]);
      await Promise.resolve(ea.addElementsToView(false));
      return true;
    } catch (error) {
      console.warn("Could not update text through ExcalidrawAutomate.", error);
    }
  }
  const api = safeGetExcalidrawApi(ea);
  if (!(api == null ? void 0 : api.getSceneElements) || !api.updateScene) {
    return false;
  }
  try {
    const elements = api.getSceneElements().map((sceneElement) => {
      return sceneElement.id === element.id ? withUpdatedText(sceneElement, text) : sceneElement;
    });
    api.updateScene({
      elements,
      commitToHistory: true
    });
    return true;
  } catch (error) {
    console.warn("Could not update text through Excalidraw API.", error);
    return false;
  }
}
async function insertNewTextElement(ea, view, text, width) {
  var _a, _b, _c;
  if (!ea.addText || !ea.addElementsToView) {
    return false;
  }
  try {
    const api = safeGetExcalidrawApi(ea);
    const appState = (_b = (_a = api == null ? void 0 : api.getAppState) == null ? void 0 : _a.call(api)) != null ? _b : {};
    (_c = ea.reset) == null ? void 0 : _c.call(ea);
    applyCurrentTextStyle(ea, appState);
    const point = getViewportCenterScenePoint(view, appState);
    ea.addText(point.x, point.y, text, {
      width
    });
    await Promise.resolve(ea.addElementsToView(false));
    return true;
  } catch (error) {
    console.warn("Could not insert text through ExcalidrawAutomate.", error);
    return false;
  }
}
function withUpdatedText(element, text) {
  const next = {
    ...element,
    text
  };
  if ("rawText" in next) {
    next.rawText = text;
  }
  if ("originalText" in next) {
    next.originalText = text;
  }
  return next;
}
function safeGetExcalidrawApi(ea) {
  var _a, _b;
  try {
    return (_b = (_a = ea.getExcalidrawAPI) == null ? void 0 : _a.call(ea)) != null ? _b : null;
  } catch (error) {
    console.warn("Could not access Excalidraw API.", error);
    return null;
  }
}
function applyCurrentTextStyle(ea, appState) {
  if (!ea.style) {
    return;
  }
  copyStyleValue(appState, "currentItemStrokeColor", ea.style, "strokeColor");
  copyStyleValue(appState, "currentItemBackgroundColor", ea.style, "backgroundColor");
  copyStyleValue(appState, "currentItemFontFamily", ea.style, "fontFamily");
  copyStyleValue(appState, "currentItemFontSize", ea.style, "fontSize");
  copyStyleValue(appState, "currentItemTextAlign", ea.style, "textAlign");
  copyStyleValue(appState, "currentItemOpacity", ea.style, "opacity");
  copyStyleValue(appState, "currentItemRoughness", ea.style, "roughness");
}
function copyStyleValue(source, sourceKey, target, targetKey) {
  const value = source[sourceKey];
  if (value !== void 0 && value !== null) {
    target[targetKey] = value;
  }
}
function getViewportCenterScenePoint(view, appState) {
  var _a, _b, _c;
  const containerEl = isObject(view) && isHTMLElementLike(view.containerEl) ? view.containerEl : null;
  const drawingEl = containerEl == null ? void 0 : containerEl.querySelector(".excalidraw");
  const rect = (_a = drawingEl != null ? drawingEl : containerEl) == null ? void 0 : _a.getBoundingClientRect();
  const width = (_b = rect == null ? void 0 : rect.width) != null ? _b : window.innerWidth;
  const height = (_c = rect == null ? void 0 : rect.height) != null ? _c : window.innerHeight;
  const scrollX = toNumber(appState.scrollX, 0);
  const scrollY = toNumber(appState.scrollY, 0);
  const zoom = getZoomValue(appState.zoom);
  return {
    x: Math.round((width / 2 - scrollX) / zoom),
    y: Math.round((height / 2 - scrollY) / zoom)
  };
}
function getZoomValue(value) {
  const zoom = isObject(value) ? toNumber(value.value, 1) : toNumber(value, 1);
  return zoom > 0 ? zoom : 1;
}
function toNumber(value, fallback) {
  return typeof value === "number" && Number.isFinite(value) ? value : fallback;
}
function isObject(value) {
  return typeof value === "object" && value !== null;
}
function isHTMLElementLike(value) {
  return value instanceof HTMLElement || isObject(value) && typeof value.querySelector === "function" && typeof value.getBoundingClientRect === "function";
}
